name: My First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout-repo
              uses: actions/checkout@v4

            - name: List and Read file
              run: |
                echo "My First Github Action Job"
                ls -ltra
                cat README.md
            - name: ASCII file
              run: cowsay -f dragon "Run for cover, I feel a sneeze coming on.>> dragon.txt
            
            #- name: List Files
            #  run: ls
            
            #- name: Read the files
            #  run: cat README.md
            
        